### ISSUE TITLE
Barcode scanner

### ISSUE THREAD

**Issue by markfillmore** [casinocoin/brm-issues#1]
barcode scanner not working on Samsung Galaxy S10e droid V 10 and Samsung Galaxy Tab S4 droid v 9

**Comment by Marec4** [comment]
Have the same issue. On sending tab, the Scan button doesn't work.

Device: Samsung J3 2017
OS: Android
OS 8
App Version 0.1.66

**Comment by ajochems** [comment]
Fixed in version 0.1.67
