### ISSUE TITLE
Restore references 10 words

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/brm-issues#15]
Steps:
Open a new install of BRM
Tap Restore Account
Don’t enter any words
Tap Restore Wallet

Result:
“Please enter all 10 words...” sentence is displayed

Change required:
Change 10 to 12
![F23B545C-BC80-4B8B-B6C6-5DDDC222D27D](https://user-images.githubusercontent.com/2853264/76506500-2b48d000-6443-11ea-9fee-f2b9ae395bb3.png)

**Comment by ajochems** [comment]
Fixed in version 0.1.67
