### ISSUE TITLE
home screen not fully showing

### ISSUE THREAD

**Issue by jesjredhca** [casinocoin/brm-issues#3]
on the note 8+, when i open the app, the top is cropped and the five buttons at the top of the app are barely showing 
![Home Screen](https://user-images.githubusercontent.com/61526782/75403761-78faff80-58bd-11ea-9d85-a7da09f57e2e.jpg)

**Comment by jesjredhca** [comment]
when i closed the app and went back in, this was fixed, since i first initiated the app, my kyc was approved, maybe that is part of it?

**Comment by justfordaniel** [comment]
im getting something like this on the first open after register but then it opens normally after until i do this ........  

github wont let me upload the video but if you search videofort3nshi you can see it

phone: G3121
os: android 8.0.0

**Comment by Marec4** [comment]
Had the same issue. After restarting the app, it was fixed.

Device: Samsung J3 2017
OS: Android
OS 8
App Version 0.1.66

**Comment by ajochems** [comment]
Had to do with fullscreen mode which has been causing a lot of issues on Android. We decided to remove fullscreen mode and this is fixed in version 0.1.67.
