### ISSUE TITLE
Scan button not working

### ISSUE THREAD

**Issue by Makanakis** [casinocoin/brm-issues#5]
When trying to send CSC using the Scan button, the button seems to be active and reacts to the click but nothing happens.

**Comment by Makanakis** [comment]
Android, Phone is Oppo RX17 Pro [https://www.oppo.com/uk/smartphone-rx17-pro/?utm_source=Google_Search&utm_medium=cpc&gclid=EAIaIQobChMInaCn1dDx5wIVzbHtCh3mgAktEAAYASAAEgIWS_D_BwE](url)

**Comment by ajochems** [comment]
QR Code scanning is fixed in version 0.1.67
