### ISSUE TITLE
About page says Testnet

### ISSUE THREAD

**Issue by Marec4** [casinocoin/brm-issues#9]
About page in BRM says "Bankroll Manager: Version (testnet)". Seems to be hardcoded.
![Image from iOS](https://user-images.githubusercontent.com/25827470/76388940-ef463a00-6372-11ea-90f5-b7233e09f0d1.png)

Device: iPhone 6s
OS: iOS 13.3.1
BRM version: 0.1.66

**Comment by ajochems** [comment]
Fixed in version 0.1.67
